---
title: "Queen Quality"
author: "Dylan Ryals"
date: "2026-02-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

Genomic Selection from skim-seq of queens and phenotypic records

```{r setup, include=FALSE}
library(tidyverse)
library(Matrix)
library(cowplot)
library(readxl)
library(corrplot)
library(ggrepel)
library(lme4)
library(sjPlot)
library(usmap)
library(multcompView)
library(colorspace)

select = dplyr::select
rename = dplyr::rename
plot_grid = cowplot::plot_grid
theme_set(theme_bw())

se = function(x) sqrt(var(x, na.rm = T)/length(x))

setwd("/home/dylan/Documents/bees/harpurlab/project/gensel/tarpy/queen-quality")
```

# phenotypes and genomic structure 
```{r}
#read phenotypic data
pheno = read.csv("data/cleaned_pheno.csv")
  pheno$loc.old = pheno$loc.fix

  #pool small factors
    small = pheno %>% group_by(loc.fix) %>% 
      summarise(n = n()) %>% 
      filter(n<5)
    
    pheno$loc.fix[pheno$loc.fix %in% small$loc.fix] = "USA"
  
  loclevels = c("USA", sort(unique(pheno$loc.fix[pheno$loc.fix != "USA"])) )
  
  pheno$loc.fix = factor(pheno$loc.fix, levels = loclevels)
  
  #pheno trends
    pheno.rm = pheno %>% 
    filter(!is.na(m.Body) & !is.na(v.Sperm) & !is.na(year))
    
  #tukey test and comp letters
    
  #weight
    
    pheno.rm$m.Body.resid = lm(m.Body ~ as.factor(year), data = pheno.rm)$residual
    
    anova.w <- aov(m.Body.resid ~ loc.fix, data = pheno.rm)
  
    # Tukey's test
    tukey.w <- TukeyHSD(anova.w, "loc.fix")
    
    # compact letter display
    cld.w <- multcompLetters4(anova.w, tukey.w)
    
  #viability
    pheno.rm$v.Sperm.resid = lm(v.Sperm ~ as.factor(year), data = pheno.rm)$residual
    
    anova.v <- aov(v.Sperm.resid ~ loc.fix, data = pheno.rm)
  
    # Tukey's test
    tukey.v <- TukeyHSD(anova.v, "loc.fix")
    
    # compact letter display
    cld.v <- multcompLetters4(anova.v, tukey.v)
    
    cld.all = data.frame(
      sig = as.data.frame.list(cld.w$loc.fix)$Letters,
      loc.fix = rownames(as.data.frame.list(cld.w$loc.fix)),
      pheno.name = "Body Mass"
    )
    
  
  pheno.long = pheno.rm %>% 
    select(gc_id, m.Body, v.Sperm, loc.fix, year) %>% 
    pivot_longer(cols = c("m.Body", "v.Sperm"), names_to = "pheno", values_to = "value")
  
    pheno.trans = data.frame(pheno = c("m.Body", "v.Sperm"),
                             pheno.name = c("Body Mass", "Sperm Viability"))
    pheno.long = pheno.long %>% left_join(pheno.trans)
    
      #state summaries
      state.sum = pheno.long %>% group_by(loc.fix, pheno) %>% 
        summarise(mean = mean(value), se = se(value)) %>% as.data.frame()
      
      state.sum
  
  
  p.phenoLoc = ggplot(pheno.long, aes(x = loc.fix, y = value)) + 
     geom_boxplot(outliers = F, color = 'red')+
    # geom_beeswarm(method = "compactswarm", 
    #               size = 0.5, cex = 0.5, alpha = 0.5) + 
    geom_jitter(height = 0, width = 0.2, alpha = 0.5, size = 0.8) + 
    facet_wrap(~pheno.name, scales = "free_y", nrow = 2) + 
    labs(x = "Location", y = "Phenotypic Value") +
    geom_text(data = cld.all, aes(label = sig, y = 285, 
                                  x = loc.fix),
              size = 2) +
    theme(axis.text.x = element_text(size = 7))
    
  #p.phenoLoc
    #dummy text to align panels A and B for body mass
    blankdat = data.frame(x = NA, sig = NA, pheno.name = "Body Mass")
  
  p.phenoYear = ggplot(pheno.long, aes(x = year, y = value)) + 
    geom_jitter(height = 0, width = 0.1, alpha = 0.5, size = 0.8) + 
    geom_smooth(method = 'lm', color = 'red', linewidth = 0.5) +
    scale_x_continuous(breaks = seq(2016, 2026, 2)) +
    facet_wrap(~pheno.name, scales = "free_y", nrow = 2) + 
    geom_text(data = blankdat, aes(label = sig, y = 285, 
                                  x = x),
              size = 2) +
    labs (x = "Year", y = NULL) +
    theme(axis.text.x = element_text(size = 7))
  p.phenoYear
  
#phenotype PCA
   
  pheno.num = pheno %>% 
    select(m.Body, v.Sperm, l.Sperm, t.Sperm, w.Head, w.Thorax, d.Spermatheca) %>% 
    as.matrix() %>% apply(MARGIN = 2, FUN = as.numeric)
  
  #summary statistics
  rangen = function(x){range(x, na.rm = T)}
  apply(pheno.num, 2, rangen)
  apply(pheno.num, 2, se)
  
  p.cor = pheno.num %>% cor(use = 'complete.obs')
  corrplot(p.cor)
  
  pdf(file = "fig/supFig2_phenoCor", height = 10, width = 10)
    corrplot(p.cor)
  dev.off()
  
  pheno.scale = pheno.num %>% apply(MARGIN = 2, FUN = scale)
  pheno.scale[is.na(pheno.scale)] = 0
  
  pca.pheno = pheno.scale %>% 
    prcomp(center = F, scale = F) 
  
  
    pcapoints = as.data.frame(pca.pheno$x)
      pcapoints$loc.fix = pheno$loc.fix
      
    pcaload = as.data.frame(pca.pheno$rotation[,1:2])
      pcaload$pheno = rownames(pcaload)
      
      #name change
      names2 = c("BM", "SV", "TVS", "TS", "HW", "TW", "SD")
      pcaload = cbind(pcaload, names2)
      
      pcazero = pcaload %>% mutate(PC1 = 0, PC2 = 0)
      
      pcaload = rbind(pcaload, pcazero)
      
      pcascale = 10
      
      pcaload = pcaload %>% 
        mutate(PC1 = PC1 * pcascale,
               PC2 = PC2 * pcascale)
      pcatext = pcaload %>% filter(PC1 != 0)
      
  #variance explained
      pvarexp = round(summary(pca.pheno)$importance[2,], 3) * 100
      
      shapes = data.frame(t(table(pcapoints$loc.fix)),
                    shapea = c(19, rep(c(17,19), 5)),
                    shapeb = c("A", rep(c("B","A"), 5))
                  )
      pcapoints = pcapoints %>% 
        left_join(shapes %>% select(loc.fix = Var2, shapea, shapeb))
      
  #plot
  p.ppca = ggplot() + 
    geom_point(data = pcapoints, aes(x = PC1, y = PC2, color = loc.fix, shape = loc.fix),
               alpha = 1) + 
    geom_line(data = pcaload, aes(x = PC1, y = PC2, group = names2),
              arrow = arrow(ends = "first", length = unit(10, "pt"))) + 
    geom_label_repel(data = pcatext, aes(x = PC1, y = PC2, label = names2)) + 
      scale_shape_manual(name = "Location",
                         labels = as.character(shapes$Var2),
                         values = shapes$shapea)+
      scale_color_manual(name = "Location",
                         labels = as.character(shapes$Var2),
                         values = c("gray", qualitative_hcl(n=10, palette = "Dark3")))+
    labs(y = paste0("PC2 (", pvarexp[2], "%)"), x = paste0("PC1 (", pvarexp[1], "%)"),
         color = "Location") +
    theme(legend.key.size = unit(1.0,"line")) +
         guides(colour = guide_legend(override.aes = list(size=3)))
  
  p.ppca
  
  pheno.num.long = as.data.frame(pheno.num) %>% 
    mutate(gc_id = pheno$gc_id) %>%
    pivot_longer(cols = -gc_id)
  
  
  p.phenocomp = plot_grid(p.phenoLoc, p.phenoYear, p.ppca, labels = "AUTO",
                          nrow = 1, rel_widths = c(0.65, 0.65, 1))
  p.phenocomp
  
  ggsave(p.phenocomp, filename = "fig/fig2_phenotypes.pdf",
         width = 10, height = 5)
  
  
#output table of summary values
  ntab = data.frame(table(pheno.rm$loc.fix)) %>% rename(Effect = 1, N = 2)
  
  vlm = lm(v.Sperm ~ loc.fix + year, data = pheno.rm)
  wlm = lm(m.Body ~ loc.fix + year, data = pheno.rm)
  coef = rbind(
                data.frame(summary(vlm)$coefficients) %>% 
                  mutate(trait = "Sperm Viability (prop)"),
                data.frame(summary(wlm)$coefficients) %>% 
                  mutate(trait = "Body Mass (mg)")
              )
  coef$effect = gsub("1|loc.fix", "", rownames(coef))
  rownames(coef) = NULL
  colnames(coef) = c("est", "se", "t", "p", "trait", "Effect")
  coef = coef %>%
    mutate(text = paste0(round(est,3), " (", round(se,3), ")")) %>% 
    filter(Effect != "(Intercept)") %>% 
    select(trait, Effect, text) %>% 
    pivot_wider(values_from = text, names_from = trait) %>% 
    left_join(ntab)
  
  coef$N[coef$Effect == 'year'] = nrow(pheno.rm)
  
  write.csv(coef, file = "data/effect_sumary.csv", 
            row.names = F, quote = F)

#genotype PCA
  eig = read.delim("data/samples-pca.eigenval", header = F)
    eig$perc = eig$V1 / sum(eig$V1)
    eig$x = 1:nrow(eig)
    
    eig %>% filter(x < 25) %>% 
    ggplot(aes(y = perc, x = x)) + geom_col()
    
    eig$perc2 = round(eig$perc * 100, 2)

  pca.geno = read.delim("data/samples-pca.eigenvec", header = F, sep = "")[,c(1,3:5)]
    colnames(pca.geno) = c("gc_id", "PC1", "PC2", "PC3")
    
    pca.geno = pca.geno %>% 
      left_join(pheno %>% select(gc_id, loc.fix, year, v.Sperm, m.Body))
    
    pca.geno$loc.fix[is.na(pca.geno$loc.fix)] = "USA"
  
    
    #hcl_palettes("qualitative", plot = TRUE)
      #try to add shapes for definition
      shapes = data.frame(t(table(pca.geno$loc.fix)),
                          shapea = c(19, rep(c(17,19), 5)),
                          shapeb = c("A", rep(c("B","A"), 5))
                        )
      
    pca.geno = pca.geno %>% 
      left_join(shapes %>%  select(loc.fix = Var2, shapea, shapeb))
  
    p.genopca = ggplot(pca.geno, aes(x = PC1, y = PC2, color = loc.fix, shape = loc.fix)) + 
      geom_point(size = 1.5) +
      scale_shape_manual(name = "Location",
                         labels = as.character(shapes$Var2),
                         values = shapes$shapea)+
      scale_color_manual(name = "Location",
                         labels = as.character(shapes$Var2),
                         values = c("gray", qualitative_hcl(n=10, palette = "Dark3")))+
      labs(color = "Location", 
           x = paste0("PC1 (", eig$perc2[1], "%)"),
           y = paste0("PC2 (", eig$perc2[2], "%)")) +
      theme(legend.key.size = unit(1.0,"line")) +
      guides(colour = guide_legend(override.aes = list(size=3)))
    
    p.genopca
    
#admixture plotting
    #read admix data
    admix = cbind(read.delim("data/finaladmix.fam", header = F, sep = "")[,1],
                  read.delim("data/finaladmix.4.Q", header = F, sep = "")
                  )
      colnames(admix)[1]="gc_id"
      
    reffam = read.delim("references/refData.txt")
    
    #verify lineage identity
    lins = admix %>% left_join(reffam %>% select(gc_id = SRR, lineage)) %>% 
      filter(grepl ("SRR", gc_id)) %>%
      pivot_longer(starts_with("V")) %>%
      group_by(name, lineage) %>%
      mutate(m = mean(value)) %>% ungroup %>% 
      group_by(name) %>% arrange(desc(m)) %>% slice(1) %>% select(lineage, name)
    
    #rename
    admix = admix %>% rename(A = V4, M = V1, C = V2, O = V3) %>% 
      left_join(pheno %>% select(gc_id, loc.fix))
    
    #summary table
    rangepaste = function(x){
      y = round(range(x, na.rm = T),3)
      return(paste0(y[1], ", ", y[2]))
      }
    
    admix.sumtab = admix %>% 
      pivot_longer(cols = c("A", "M", "C", "O"),
                   names_to = "lineage") %>% 
      rename(location = loc.fix) %>% 
      filter(!is.na(location)) %>% 
      group_by(location, lineage) %>% 
      summarise(range = rangepaste(value),
                mean = round(mean(value),3),
                se = round(se(value),3))
    
    write.table(admix.sumtab, file = "data/admix_summary.tsv",
              quote = F, row.names = F, sep = "\t")
    
    #admixture bar chart
    admix.bar = admix 
    
      #add bar id
      admix.bar = admix.bar %>% arrange(loc.fix, A)
      admix.bar$barid = (1:nrow(admix.bar))
      #melt --- long format
      admix.long = admix.bar %>% 
        pivot_longer(cols = c("A", "M", "C", "O"), values_to = "value",
                     names_to = "fam") %>% 
        mutate(fam = factor(fam, levels =c("A", "M", "C", "O")))
      
          #admixture bar chart
   p.admix = ggplot(data = admix.long %>% filter(!is.na(loc.fix))) +
      geom_bar(aes(x = as.factor(barid), y = value, fill = fam), 
               stat='identity', width = 1) +
      facet_grid(cols = vars(loc.fix), scales = "free_x") +
      scale_fill_brewer(palette = "PRGn") +
      labs(x = NULL, y = "Proportion of Genome", fill = "Lineage") + 
      theme(axis.text.x = element_blank(),
            axis.ticks.x = element_blank())
   p.admix
   
   #admix summary
   admix %>% filter(!is.na(loc.fix)) %>% 
     summarise(varA = var(A), varM = var(M), varO = var(O), varC = var(C)) %>% 
     as.data.frame()
   
   
   admix.sum = admix %>% 
     filter(!is.na(loc.fix)) %>% 
     group_by(loc.fix) %>% 
     summarise(M = mean(M), C = mean(C), O = mean(O), A = mean(A)) %>% as.data.frame()
   admix.sum

  # 
  # p.distr = ggplot(pheno.num.long, aes(x = name, y = value)) + 
  #   geom_violin() + 
  #   geom_boxplot(width = 0.5, color= 'red')+
  #   facet_wrap(~name, scales = "free") + 
  #   labs(x = NULL) + 
  #   theme(axis.text.x = element_blank())
  # 
  # p.pcomb = plot_grid(p.distr, p.ppca)
  # p.pcomb
  # 
  # ggsave(p.pcomb, filename = "fig/figS1_allpheno.pdf",
  #      width = 10, height = 5)

#correlations b/w admixture and phenotypes
  admixpheno = admix %>% 
    left_join(pheno %>% 
                select(gc_id, m.Body, v.Sperm)) %>% 
    filter(!is.na(m.Body))
  
  admixphenocor = admixpheno %>% select(m.Body, v.Sperm, A, M, C, O) %>% as.matrix
  corrplot(cor(admixphenocor))
  
  #models
  
  cor(admixpheno$m.Body, admixpheno$C)
  
  apmod = lm(m.Body ~ loc.fix + C , data = admixpheno)
  summary(apmod)
  
  massmod = lmer(m.Body ~ M + C + O + (1|loc.fix) , data = admixpheno)
  AIC(massmod)
  summary(massmod)
  
  plot_model(massmod)
  

#effects of location and year 
  pheno2 = pheno
  pheno2$loc.fix[pheno2$loc.fix %in% c("NCA", "SCA", "CA")] = "CA"
  pheno2 = pheno2 %>% 
    mutate(loc.fix = as.factor(loc.fix),
           loc.fix = relevel(loc.fix, "USA"))
  
  summary(lm(v.Sperm ~ year + loc.fix, data = pheno2))
  
  summary(lm(m.Body ~ year + loc.fix, data = pheno2))
  
#Fstat and pheno
  fstat = read.delim("data/samples-filter.het") %>% 
    mutate(het = (N_SITES - O.HOM.) / N_SITES) %>% 
    select(gc_id = INDV, fstat = `F`, het) %>% 
    left_join(admixpheno)
  
  hist(fstat$het)
  mean(fstat$het)
  sd(fstat$het)
  
    fcor = fstat %>% select(m.Body, v.Sperm, fstat) %>% as.matrix()
    corrplot(cor(fcor, use = "pairwise.complete.obs"))
  
  ggplot(fstat, aes(x = fstat, y = v.Sperm)) + 
    geom_point(alpha = 0.5)
  

#collection locations
  sampling = pheno %>% select(loc.old) %>% 
    filter(loc.old != "USA")
    sampling$loc.old[sampling$loc.old %in% c("NCA", "SCA")] = "CA"    
    
    sampling = sampling %>% 
      rename(state = loc.old) %>% 
      group_by(state) %>% 
      summarise(N = n())
    
    state2 = sort(c(state.abb, "DC"))
    
    labcol = ifelse(state2 %in% sampling$state, "white", NA)
      labcol[state2 %in% c("GA", "HI")] = "black"
  
  p.map = plot_usmap(
    #include = unique(sampling$states),
    color = 'gray',
    data = sampling,
    values = "N",
    labels = T,
    label_color = labcol,
  ) +
  scale_fill_viridis_b(
    trans = 'log',
    breaks = c(1, 5, 20, 180),
    option = "G"
  )  + 
  theme(text = element_text(size = 10))
  
p.map
  
  
#compound sampling figure
  
p.a = cowplot::plot_grid(p.map, p.genopca, labels = c("A", "B"))
p.samplecom = cowplot::plot_grid(p.a, p.admix, nrow = 2, labels = c(NA, "C"))
p.samplecom

  
  ggsave(p.samplecom, filename = "fig/fig1_samples.pdf",
         width = 10, height = 7)
  
```


# GWAS analysis: all locations
```{r}
#GWAS 
  
  #TODO: update with LOCO
  
  #viability
  v.mlma = read.delim("data/qq_vsperm.loco.mlma", sep = "")
  v.mlma$padj = p.adjust(v.mlma$p, method = "bonferroni", n = nrow(v.mlma))
  v.mlma$logp = log(v.mlma$padj, base = 10)* -1
  v.mlma$lograwp = log(v.mlma$p, base = 10) * -1
  
  #pub-friendly plot
  v.plot = v.mlma %>% 
    arrange(Chr, bp) %>% 
    mutate(order = 1:nrow(v.mlma))
  
  v.plot$color = ifelse(v.plot$Chr%%2 ==0, "A", "B" )
    
    
  #weight
  w.mlma = read.delim("data/qq_weight.loco.mlma", sep = "")
  w.mlma$padj = p.adjust(w.mlma$p, method = "bonferroni", n = nrow(w.mlma))
  w.mlma$logp = log(w.mlma$padj, base = 10)* -1
  w.mlma$lograwp = log(w.mlma$p, base = 10) * -1
  
  #pub-friendly plot
  w.plot = w.mlma %>% 
    arrange(Chr, bp) %>% 
    mutate(order = 1:nrow(w.mlma))
  
  w.plot$color = ifelse(w.plot$Chr%%2 ==0, "A", "B" )
  
  #together
  
  man.plot = rbind(w.plot %>% mutate(trait = "Body Mass"),
                   v.plot %>% mutate(trait = "Sperm Viability"))
  
  p.man = ggplot(man.plot, aes(x = order, y = lograwp, color = color)) + 
   geom_point() + 
    geom_hline(aes(yintercept = 
                     (-1 * log(0.05 / nrow(w.plot), base = 10))),
           linetype = 2, col = 'red', linewidth = 1) +
    facet_wrap(~trait, nrow = 2) +
    ylab(expression("-log"[10]*"(p)"))+
    labs(x = NULL) +
    scale_color_manual(values = c("black", "darkgray"))+
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          legend.position = 'none',
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank())
  p.man
  
    ggsave(p.man, filename = "fig/fig3a_manhattan.pdf",
         width = 6, height = 7)
  
#output top hits
  all.mlma.l = list(v.mlma, w.mlma)
  traits = c("v.Sperm", "m.Body")
  
  all.mlma = data.frame(SNP = NA,
                        Chr = NA, 
                        bp = NA, 
                        A1 = NA, 
                        A2 = NA,
                        b = NA,
                        p = NA, 
                        padj = NA,
                        trait  = NA)
  
  for(i in 1:length(all.mlma.l)){
    x = all.mlma.l[[i]] %>% filter(padj < 0.05) %>% arrange(padj) %>%
          select(SNP, Chr, bp, A1, A2, b,p, padj) %>% 
      mutate(trait = traits[i])
    all.mlma = rbind(all.mlma, x)
  }
  all.mlma = all.mlma[-1,] %>% 
    arrange(Chr, bp)
  
  # write.csv(all.mlma, file = "data/gwashits.csv",
  #           row.names = F, quote = F)
  # 
  
  N = nrow(pheno)
  
#variance explained by top hits
  varexp = v.mlma %>% filter(padj < 0.05) %>% 
    mutate(varexp = (2 * b**2 * Freq * (1-Freq)) / 
                    (2 * b**2 * Freq * (1-Freq) +
                     se**2 * 2 * N * Freq * (1-Freq)) 
           )
  
# #compare against GREML h2 
#   greml = read.delim("data/greml_weight.snp.blp",
#                      header = F, sep = "")
#     colnames(greml) = c("SNP", "alt", "G1", "G2", "G3", "G4", "R")
#     greml = greml %>% 
#       mutate(G = G1 + G2 + G3 + G4)
#     
#     varexp = varexp %>% 
#       left_join(greml %>% select(SNP, G))
#     
    #format for output
    varexp.out = varexp %>%
      mutate(chr = gsub("([0-9]*)[:][0-9]*", "\\1", SNP),
             pos = gsub("[0-9]*[:]([0-9]*)", "\\1", SNP)) %>%
      mutate(Freq = round(Freq,3),
             b = round(b,4),
             padj = paste0("\'", formatC(padj, format = "e", digits = 2)),
             varexp = round(varexp, 4),
             #G = round(G,4),
             pos = paste0("\'", pos)) %>%
      arrange(desc(varexp)) %>%
      select(`Chromosome` = chr, `Position` = pos,
             `Allele Frequency` = Freq, `SNP effect` = b,
             `Pvalue` = padj, `Variance Explained` = varexp)#,
             #`SNP heritability` = G)
    
    write.csv(varexp.out, file = "data/variance_explained.csv",
              row.names = F)
  
  
#QQplots 
  qqPlot <- function(pval, truncate = FALSE, ylim=NULL, thinThreshold=NULL, ci=TRUE, ...) 
{
  # pvalue is a vector of p-values
  # truncate is T/F whether to truncate the y-axis (observed) to the same limits as the x-axis (expected)
  # thin is whether to thin insignificant p-values
  
  pval <- -log10(sort(pval)) # sort() removes NAs
  n <- length(pval)
  a <- 1:n
  b <- a/n
  x <- -log10(b)
  
  if (!is.null(thinThreshold)){
    breaks <- seq(from=0, to=thinThreshold, length.out=11)
    pval.cut <- cut(pval, breaks=breaks, right=FALSE)
    #quant <- quantile(pval[pval < thinThreshold], probs=1:10/10)
    #pval.cut <- cut(pval, breaks=c(0, quant), right=FALSE)
    ind.list <- list()
    for (level in levels(pval.cut)){
      sel <- which(pval.cut == level)
      ind.list[[level]] <- sel[sample.int(length(sel), min(1000, length(sel)))]
    }
    ind.list[["max"]] <- which(pval >= thinThreshold)
    ind <- unlist(ind.list, use.names=FALSE)
    ind <- sort(ind) # sorting necessary for polygon, below
  } else {
    ind <- 1:n
  }
  
  
  char <- rep(1,n)
  if(!is.logical(truncate) | truncate){
    if (is.logical(truncate)){
      maxx <- max(x)+2  
    } else {
      maxx <- min(truncate, max(pval))
    }
    
    ylm <- c(0,maxx)
    ylb <- expression(paste(-log[10], "(observed P) - truncated"))
    nx <- length(which(pval > maxx))
    if(nx > 0){
      pval[1:nx] <- maxx
      char[1:nx] <- 2
    }
    
  } else {
    ylm <- ylim
    ylb <- expression(paste(-log[10], "(observed P)"))
  }
  plot(x[ind], pval[ind], type = "n", ylim = ylm, ylab = ylb,
       xlab = expression(paste(-log[10], "(expected P)")), ...)
  # upper and lower have already been subset
  if (ci){
    upper <- qbeta(0.05, a[ind], rev(a)[ind])
    lower <- qbeta(0.95, a[ind], rev(a)[ind])

    polygon(-log10(c(b[ind], rev(b[ind]))), -log10(c(upper, rev(lower))), density=NA, col="gray")
  }
  points(x[ind], pval[ind], pch = 19, ...)  
  abline(0,1,col="red")  
}
    


  
pdf(file = "fig/supFig1_qq.pdf",
    height = 7, width = 4)
  par(mfrow = c(2,1))
  qqPlot(w.mlma$p)
  qqPlot(v.mlma$p)
dev.off()
  
par(mfrow = c(1,1))
plot.new()
  
```

## GWA: select locations (WIP)
```{r, eval=F}

loc.sigsites = data.frame(loc = NA,
                          trait = NA,
                          snp = NA,
                          chr = NA,
                          bp = NA,
                          p = NA)

for(LOC in c("HI", "CA", "GA")){

 #viability
  v.mlma = read.delim(paste0("data/qq_vsperm_", LOC, ".loco.mlma"), sep = "")
  v.mlma$padj = p.adjust(v.mlma$p, method = "bonferroni", n = nrow(v.mlma))
  v.mlma$logp = log(v.mlma$padj, base = 10)* -1
  v.mlma$lograwp = log(v.mlma$p, base = 10) * -1
  
  #pub-friendly plot
  v.plot = v.mlma %>% 
    arrange(Chr, bp) %>% 
    mutate(order = 1:nrow(v.mlma))
  
  v.plot$color = ifelse(v.plot$Chr%%2 ==0, "A", "B" )
    
    
  #weight
  w.mlma = read.delim(paste0("data/qq_weight_", LOC, ".loco.mlma"), sep = "")
  w.mlma$padj = p.adjust(w.mlma$p, method = "bonferroni", n = nrow(w.mlma))
  w.mlma$logp = log(w.mlma$padj, base = 10)* -1
  w.mlma$lograwp = log(w.mlma$p, base = 10) * -1
  
  #pub-friendly plot
  w.plot = w.mlma %>% 
    arrange(Chr, bp) %>% 
    mutate(order = 1:nrow(w.mlma))
  
  w.plot$color = ifelse(w.plot$Chr%%2 ==0, "A", "B" )
  
  #together
  
  man.plot = rbind(w.plot %>% mutate(trait = "Body Mass"),
                   v.plot %>% mutate(trait = "Sperm Viability"))
  
  # ggplot(man.plot, aes(x = order, y = lograwp, color = color)) + 
  #   geom_point() + 
  #   geom_hline(aes(yintercept = 
  #                    (-1 * log(0.05 / nrow(w.plot), base = 10))),
  #          linetype = 2, col = 'red', linewidth = 1) +
  #   facet_wrap(~trait, nrow = 2) +
  #   labs(y = "-log(p)", x = "Position", title = LOC) +
  #   scale_color_manual(values = c("black", "darkgray"))+
  #   theme(axis.text.x = element_blank(),
  #         legend.position = 'none')
  
  site.save = man.plot %>% 
    filter(padj < 0.05) %>% 
    mutate(loc = LOC) %>% 
    select(loc, trait, snp = SNP, chr = Chr, bp, p = padj)
  
  loc.sigsites = rbind(loc.sigsites, site.save)
  
}

#plot
  ggplot(loc.sigsites[-1,], aes(x = bp, y = (-1 * log(p, 10)))) +
    geom_point() +
    geom_hline(aes(yintercept =
                     (-1 * log(0.05, base = 10) * 3)),
           linetype = 2, col = 'red', linewidth = 1) +
    facet_grid(rows = vars(loc), cols = vars(chr), scales = "free_x") +
    labs(y = bquote(d[subscript]), x = "Position") +
    scale_color_manual(values = c("black", "darkgray"))+
    theme(axis.text.x = element_blank(),
          legend.position = 'none')


#summarize
  loc.sum = loc.sigsites %>% 
    group_by(snp) %>% 
    summarise(n = n())
  
#TODO: clumping ........

```


# Genomic Selection

CV error
```{r}
cv = read.csv("data/CV_summary.csv")

cv.long = cv %>% 
  pivot_longer(c(cor, slope), names_to = "param", values_to = "value")

  #rename
  cv.long$param[cv.long$param == "slope"] = "Slope"
  cv.long$param[cv.long$param == "cor"] = "Correlation"
  cv.long$tn[cv.long$tn == "w"] = "Body Mass"
  cv.long$tn[cv.long$tn == "v"] = "Sperm Viability"

cv.mean = cv.long %>% 
  group_by(tn, param) %>% 
  summarise(mean = mean(value),
            se = se(value))


p.cv1 = cv.long %>% filter(param == "Correlation") %>% 
  ggplot(aes(x = tn, y = value)) + 
  geom_point() + 
  geom_col(data = cv.mean %>% filter(param == "Correlation"),
           aes(x = tn, y = mean), alpha = 0.4) +
  geom_errorbar(data = cv.mean %>% filter(param == "Correlation"), 
                aes(x = tn, y = mean, ymax = mean + se, ymin = mean - se),
                width = 0.5) +
  labs(x = NULL, y = "Correlation")

p.cv2 = cv.long %>% filter(param == "Slope") %>% 
  ggplot(aes(x = tn, y = value)) + 
  geom_point() + 
  geom_col(data = cv.mean %>% filter(param == "Slope"),
           aes(x = tn, y = mean), alpha = 0.4) +
  geom_errorbar(data = cv.mean %>% filter(param == "Slope"), 
                aes(x = tn, y = mean, ymax = mean + se, ymin = mean - se),
                width = 0.5) +
  labs(x = NULL, y = "Slope")

p.cv = cowplot::plot_grid(p.cv1, p.cv2, nrow = 1)

p.cv
```


read results: quantitative
```{r}
#read phenotype file.....
pheno.blup = read.delim("data/pheno.txt",
                        header = F, sep = "")

colnames(pheno.blup) = c("iid", "locid", "PC1", "PC2", "PC3", "lsperm", "weight", "vsperm", "tsperm", 
                         "locyear", "gc_id", "pheno_id")


#pull solutions: 2-trait
  sol = read.delim("data/sol-wv.txt", sep = "", header = F)[-1,]
    colnames(sol) = c("trait", "effect", "level" ,"solution", "se")
    sol = sol %>% mutate(se = as.numeric(se),
                         solution = as.numeric(solution))  

  sol.long = sol %>% 
    filter(effect == 1) %>% select(-effect) %>% rename(bv = solution) %>% 
    mutate(trait = recode(trait, `1` = "weight", `2` = "vsperm"))
  
  sol.long = sol.long %>% 
    left_join(pheno.blup %>% select(level = iid, gc_id, locyear) %>% 
                mutate(level = as.character(level))) %>% 
    mutate(year = gsub(".*([0-9]{4})$", "\\1", locyear))
  
    sol.wide = sol.long %>%
    pivot_wider(values_from = c(se, bv), names_from = trait)

  sol.wide %>% select(starts_with("bv")) %>% pairs()
  
  #summary
  sol.long %>% 
    select(trait, bv) %>% 
    group_by(trait) %>% 
    summarise(rangepaste(bv))
  

#plot against raw pheno
  
  pbv = sol.wide%>% 
    left_join(pheno.blup %>% select(gc_id, weight, vsperm, lsperm))
  
  p.bvweight =ggplot(pbv, aes(x = weight, y = bv_weight)) +
    geom_point(alpha = 0.5) + 
    labs(x = "Body Mass (mg)", y = "Breeding Value")
  p.bvvsperm = ggplot(pbv, aes(x = vsperm, y = bv_vsperm)) + 
    geom_point(alpha = 0.5) + 
    labs(x = "Sperm Viability (%)", y = NULL)
  
  
#plot against time
  sol.time = sol.long %>% filter(locyear != "USA20XX") %>% 
    mutate(year = as.numeric(year))

  ggplot(sol.time, aes(x = year, y = bv)) + 
    geom_point() + 
    geom_smooth(method = 'lm', se = F, color = 'blue', linetype = 1) +
    facet_wrap(~trait)
  

  #model 
  w.mod = lm(bv~ year, data = sol.time %>% filter(trait == "weight"))
  v.mod = lm(bv~ year, data = sol.time %>% filter(trait == "vsperm"))
  
  summary(w.mod)
  summary(v.mod)
  
  
#TODO: use BVs not phenos
#estimate genetic gain per generation
  
  #estimated reliability from blupf90
    rel = read.delim("data/acc_bf90",
                     header = F, sep = "")
    colnames(rel) = c("trait", "effect", "level" ,"bv", "rel")
    
    hist(rel$rel[rel$trait == 1])
    hist(rel$rel[rel$trait == 2])
    
      
  
params = data.frame(trait = c("weight", "vsperm"),
                    rel = c(mean(rel$rel[rel$trait == 1]),
                            mean(rel$rel[rel$trait == 2])),
                    acc = c(0.2, 0.2),
                    sdG = c(sqrt(131), sqrt(109)),
                    sdX = c(sd(sol.time$bv[sol.time$trait == "weight"]),
                            sd(sol.time$bv[sol.time$trait == "vsperm"])))


  #difference in standardized breeding value for selected individuals

  sol.time.wide = sol.time %>% 
    select(gc_id, year, trait, bv) %>% 
    pivot_wider(names_from = "trait", values_from = "bv") %>% 
    as.data.frame()
  
  prog = data.frame(prop = rep(c(0.5, 0.1, 0.01, 0.001),2),
                         trait = c(rep("weight", 4), rep("vsperm",4)),
                         intensity = NA,
                         prog = NA)
  
  for(i in 1:nrow(prog)){
    #number of individuals for desired %
    N = ceiling(nrow(sol.time.wide) * prog$prop[i])
    #average of top N phenos
    prog$intensity[i] = mean(sort(sol.time.wide[,prog$trait[i]], 
                                  decreasing = T)[1:N])
    #progress in BV
    prog$prog[i] = prog$intensity[i] *
      params$sdG[params$trait == prog$trait[i]] *
      params$acc[params$trait == prog$trait[i]] /
      params$sdX[params$trait == prog$trait[i]]
  }
  
  #points for theoretical trend
  prog$a = NA
    prog$a[prog$trait == "weight"] = predict(w.mod, data.frame(year = 2025))
    prog$a[prog$trait == "vsperm"] = predict(v.mod, data.frame(year = 2025))
    
  prog$b = prog$a + prog$prog
  
  prog.plot = prog %>% 
    select(prop, trait, a, b) %>% 
    pivot_longer(cols = c("a", "b"), names_to = "point", values_to = "bv")
  
    prog.plot$year = ifelse(prog.plot$point == "b", 2026, 2025)
    prog.plot$trait[prog.plot$trait == "vsperm"] = "Sperm Viability"
     prog.plot$trait[prog.plot$trait == "weight"] = "Body Mass"
     
  
    sol.time.plot = sol.time
      
    sol.time.plot$trait[sol.time.plot$trait == "vsperm"] = "Sperm Viability"
    sol.time.plot$trait[sol.time.plot$trait == "weight"] = "Body Mass"
  
  
  
p.prog = ggplot(sol.time.plot, aes(x = year, y = bv)) + 
    geom_jitter(height = 0, width = 0.2, alpha = 0.5) + 
    geom_smooth(method = 'lm', se = F, color = 'red', linetype = 1) +
    geom_line(data = prog.plot,
              aes(x = year, y = bv, linetype = as.factor(prop)),
              color = 'blue') +
    facet_wrap(~trait, scales = "free") + 
    scale_x_continuous(breaks = seq(2016, 2026, 2)) +
    labs(linetype = "Proportion Selected", y = "Breeding Value",
         x = "Year") +
  theme(legend.position = "bottom")
p.prog  

  #combined plot
  p.bva = plot_grid(p.bvweight, p.bvvsperm)
  p.bvcomb = plot_grid(p.bva, p.cv, p.prog, 
                       rel_heights = c(1.2,1,1.5) , nrow = 3, labels = "AUTO",
                       scale = 0.9)
  p.bvcomb
  
  ggsave(p.bvcomb, filename = "fig/fig4_BVsummary.pdf",
         width = 8, height = 10)
  
```



